version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  groups:
    python-packages:
      patterns:
        - "*"
- package-ecosystem: "docker"
  directory: "/.devcontainer/"
  schedule:
    interval: "daily"
